package com.zzuli.jz.dao;

import com.zzuli.jz.bean.OrderLine;
import com.zzuli.jz.bean.OrderLineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    long countByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int deleteByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int insert(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int insertSelective(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    List<OrderLine> selectByExample(OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    OrderLine selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderLine record, @Param("example") OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int updateByExample(@Param("record") OrderLine record, @Param("example") OrderLineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int updateByPrimaryKeySelective(OrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jz_order_line
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int updateByPrimaryKey(OrderLine record);
}