package com.zzuli.jz.dao;

import com.zzuli.jz.bean.RolePrivilege;
import com.zzuli.jz.bean.RolePrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    long countByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int deleteByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int insert(RolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int insertSelective(RolePrivilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    List<RolePrivilege> selectByExample(RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int updateByExampleSelective(@Param("record") RolePrivilege record, @Param("example") RolePrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_role_privilege
     *
     * @mbg.generated Fri Jun 12 14:51:11 CST 2020
     */
    int updateByExample(@Param("record") RolePrivilege record, @Param("example") RolePrivilegeExample example);
}